/**
 * SimpleChart - Renders charts based on LLM-generated configuration
 *
 * This component receives a chart config from the backend (generated by LLM)
 * and renders a simple, clean visualization using recharts.
 *
 * For now, we use recharts instead of raw D3.js for simplicity.
 * The LLM provides the configuration, and recharts handles rendering.
 */

import { useState } from 'react';
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  AreaChart,
  Area,
  PieChart,
  Pie,
  ScatterChart,
  Scatter,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  Cell,
} from 'recharts';

export interface ChartConfig {
  type: 'bar' | 'line' | 'scatter' | 'pie' | 'area';
  title: string;
  description: string;
  config: {
    xField: string;
    yField: string;
    color: string;
    showLegend?: boolean;
    showGrid?: boolean;
  };
}

interface SimpleChartProps {
  data: any[];
  columns: string[];
  config: ChartConfig;
  height?: number;
}

export const SimpleChart = ({
  data,
  columns,
  config,
  height = 400,
}: SimpleChartProps) => {
  // Transform data to format expected by recharts
  const chartData = data.map((row) => {
    const obj: any = {};
    columns.forEach((col, index) => {
      obj[col] = row[index];
    });
    return obj;
  });

  const { xField, yField, color, showLegend = true, showGrid = true } = config.config;

  // Common chart components
  const commonProps = {
    data: chartData,
  };

  const renderChart = () => {
    switch (config.type) {
      case 'bar':
        return (
          <BarChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" opacity={0.3} />}
            <XAxis dataKey={xField} stroke="#888" />
            <YAxis stroke="#888" />
            <Tooltip
              contentStyle={{
                backgroundColor: '#fff',
                border: '1px solid #ccc',
                borderRadius: '4px'
              }}
            />
            {showLegend && <Legend />}
            <Bar dataKey={yField} fill={color} radius={[4, 4, 0, 0]} />
          </BarChart>
        );

      case 'line':
        return (
          <LineChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" opacity={0.3} />}
            <XAxis dataKey={xField} stroke="#888" />
            <YAxis stroke="#888" />
            <Tooltip
              contentStyle={{
                backgroundColor: '#fff',
                border: '1px solid #ccc',
                borderRadius: '4px'
              }}
            />
            {showLegend && <Legend />}
            <Line
              type="monotone"
              dataKey={yField}
              stroke={color}
              strokeWidth={2}
              dot={{ fill: color, r: 4 }}
              activeDot={{ r: 6 }}
            />
          </LineChart>
        );

      case 'area':
        return (
          <AreaChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" opacity={0.3} />}
            <XAxis dataKey={xField} stroke="#888" />
            <YAxis stroke="#888" />
            <Tooltip
              contentStyle={{
                backgroundColor: '#fff',
                border: '1px solid #ccc',
                borderRadius: '4px'
              }}
            />
            {showLegend && <Legend />}
            <Area
              type="monotone"
              dataKey={yField}
              stroke={color}
              fill={color}
              fillOpacity={0.6}
            />
          </AreaChart>
        );

      case 'scatter':
        return (
          <ScatterChart {...commonProps}>
            {showGrid && <CartesianGrid strokeDasharray="3 3" opacity={0.3} />}
            <XAxis dataKey={xField} stroke="#888" />
            <YAxis dataKey={yField} stroke="#888" />
            <Tooltip
              contentStyle={{
                backgroundColor: '#fff',
                border: '1px solid #ccc',
                borderRadius: '4px'
              }}
              cursor={{ strokeDasharray: '3 3' }}
            />
            {showLegend && <Legend />}
            <Scatter name={yField} fill={color} />
          </ScatterChart>
        );

      case 'pie':
        return (
          <PieChart>
            <Pie
              data={chartData}
              dataKey={yField}
              nameKey={xField}
              cx="50%"
              cy="50%"
              outerRadius={120}
              label
            >
              {chartData.map((entry, index) => (
                <Cell
                  key={`cell-${index}`}
                  fill={`hsl(${(index * 360) / chartData.length}, 70%, 50%)`}
                />
              ))}
            </Pie>
            <Tooltip
              contentStyle={{
                backgroundColor: '#fff',
                border: '1px solid #ccc',
                borderRadius: '4px'
              }}
            />
            {showLegend && <Legend />}
          </PieChart>
        );

      default:
        return <div>Unsupported chart type: {config.type}</div>;
    }
  };

  return (
    <div className="space-y-2">
      {config.title && (
        <div>
          <h3 className="text-sm font-semibold">{config.title}</h3>
          {config.description && (
            <p className="text-xs text-muted-foreground">{config.description}</p>
          )}
        </div>
      )}
      <ResponsiveContainer width="100%" height={height}>
        {renderChart()}
      </ResponsiveContainer>
    </div>
  );
};
